[package]
authors = ["Magnus Hoff <maghoff@gmail.com>"]
name = "slog-slack"
version = "0.1.0"

[dependencies]
slack-hook = "0.2.0"
slog = "1.5.2"

[dev-dependencies]
slog-extra = "0.1.1"
slog-term = "1.5.0"
